### ISSUE TITLE
Edit Schedule page

### ISSUE THREAD

**Issue by cocolocomoco21** [cocolocomoco21/ULCRS#18] opened 2017-11-07 19:48 UTC
Implement the page that allows the user to modify the current displayed schedule with HTML, JS, and CSS. It will also send the modified schedule through API to the backend.

**Comment by xujunjiejack** [comment] 2017-12-06 23:10
I'm going to close it because the description of the issue is outdated, and we have a iteration 3 version out there

**Closed by xujunjiejack** 2017-12-06 23:10 UTC
Labels: frontend
